/**
 * Flags `resources/read` calls for URIs this server never hands out, so
 * fail2ban can ban the caller.
 *
 * Every widget URI is generated by `widgetUriFor()` as the prefix plus a
 * numeric chord id, so a real host only ever asks for those. Scanners walk a
 * secrets wordlist through the template instead — `.env`, `.env.production`,
 * `.ssh/id_rsa` — hoping the handler reads from disk. It doesn't, but nginx
 * only sees `POST /mcp 200`, so the gpra-probe jail can't tell these from
 * ordinary traffic. This module logs one line per bad URI to the journal,
 * where the gpra-mcp-probe jail picks it up.
 */

// The literal `{id}` is what resources/templates/list advertises; a dev tool
// reading it as-is is a confused human, not a scanner.
const VALID_URI = /^ui:\/\/gpra-chord-charts\/chart\/(?:\d+|\{id\})$/;

// fail2ban bans at 3. Capping lines per request keeps one big batch from
// tripping journald's per-unit rate limit, which would also swallow every
// other log line from the service for up to 30s.
const MAX_PER_REQUEST = 5;
const MAX_URI_LENGTH = 200;

type JsonRpcMessage = { method?: unknown; params?: { uri?: unknown } };

/** URIs in a request body (single message or batch) that no real host would ask for. */
export const probedResourceUris = (body: unknown): string[] => {
  const messages = Array.isArray(body) ? body : [body];
  return messages
    .filter(
      (message): message is JsonRpcMessage =>
        typeof message === 'object' && message !== null && (message as JsonRpcMessage).method === 'resources/read',
    )
    .map((message) => message.params?.uri)
    .filter((uri) => typeof uri !== 'string' || !VALID_URI.test(uri))
    .slice(0, MAX_PER_REQUEST)
    .map((uri) => String(uri));
};

/**
 * One journal line per probe. The IP comes first and the URI is truncated and
 * percent-encoded, so the caller-controlled part has no spaces, `=` or newlines
 * and can't forge a second `ip=` for the anchored fail2ban regex.
 */
export const probeLogLine = (ip: string, uri: string): string =>
  // A lone surrogate (sent as JSON, or made by the slice) would make
  // encodeURIComponent throw, so surrogates go; it's only a log line.
  `mcp-probe ip=${ip} uri=${encodeURIComponent(uri.slice(0, MAX_URI_LENGTH).replace(/[\ud800-\udfff]/g, '?'))}`;
